apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiftlybot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: swiftlybot 
  template:
    metadata:
      labels:
        name: swiftlybot
    spec:
      containers:
      - name: swiftlybot
        image: iruka541/swiftlybot:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: swiftly-secrets